### ISSUE TITLE
Deploy to firebase

### ISSUE THREAD

**Issue by drievana** [oSoc19/gentlestudent-web#152]

**Comment by auloin** [comment]
We need to use Cloud Functions or Cloud Run for Hosting to support the full features of Nextjs.

See for a Cloud  Functions example: https://github.com/jthegedus/firebase-gcp-examples/tree/main/functions-nextjs
See for a Cloud Run example: https://github.com/jthegedus/firebase-gcp-examples/tree/main/cloudrun-nextjs

This is a blocking issue as we need to enable billing to use either of the two previous options.

**Comment by Cinezaster** [comment]
We moved away from firebase
